### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by NikolaIstvanic** [vmurahari3/CS2340_Team5_Sp17#1]
- [ ] Get all caught up with Git
- [ ] Install desired Git client on each machine
- [ ] Create repository "repository" and share with teammates
- [ ] Download, unzip, import M2
- [ ] Create branch, clone; verify modifying branch does not affect original
- [ ] Choose individual file in /src/, fill out, commit, and push
- [ ] Add readme and delete useless text file
- [ ] Create build file

Done done criteria:
Working knowledge of GitHub. Repository where each team member filled out his file in /src/.
