### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by NikolaIstvanic** [vmurahari3/CS2340_Team5_Sp17#2]
- [ ] Download, extract, and run file to see if executable
- [ ] Create ClassStanding class; add enum for standing
- [ ] Add class standing attribute in Student; getter/setter for class standing; create new constructor to take class standing; update toString
- [ ] Update View in order to accept class standing
- [ ] Update Controller to handle class standing
- [ ] Run code

Done done criteria:
Finalized application which allows user to enter student information (including class standing).
