### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by NikolaIstvanic** [vmurahari3/CS2340_Team5_Sp17#3]
- [ ] Create context diagram for system
- [ ] Create 10 user stories; each member choose one and describe it
- [ ] Create Android project and import to Git
- [ ] Create login screen
- [ ] If login is successful, go on to application; else, notify of bad login attempt

Done done criteria:
A functioning application which allows a user to enter a username and password which has the normal functionality as most login screens (if successful, move on to application; else, display incorrect login).
